name: Windows - CRD (No Inputs Test)

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
      - name: Download Keep-Alive Script
        shell: cmd
        run: |
          curl.exe -L -o time.py "https://www.dropbox.com/scl/fi/ox42qglbf6fsnm9erf8cw/timeli
mit.py?rlkey=opyeqgum1k95kud81xlc7d66r&dl=1"
          pip install psutil --quiet

      - name: Install and Configure Chrome Remote Desktop
        shell: powershell
        run: |
          # THIS IS ONLY A TEST. IT WILL FAIL IF RUN.
          # WE ARE ONLY CHECKING IF THE "Run workflow" BUTTON APPEARS.
          Write-Host "[!] This is a test workflow."
          $FullCommand = '--code="FAKE_CODE_FOR_TESTING"'
          $AccessPin = '123456'
          # The rest of the script would fail, which is expected for this test.
          Write-Host "[+] Test script loaded."


      - name: Keep Runner Alive
        run: python time.py
