name: Windows - RDP with tmate Tunnel

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
      - name: Install All Tools & Dependencies
        shell: cmd
        run: |
          @echo off
          echo "[!] Installing dependencies..."
          curl -s -L -o time.py "https://www.dropbox.com/scl/fi/ox42qglbf6fsnm9erf8cw/timelimit.py?rlkey=opyeqgum1k95kud81xlc7d66r&dl=0"
          pip install psutil --quiet

      - name: Configure System & Enable RDP
        shell: powershell
        run: |
          Write-Host "[!] Setting User Password..."
          $password = "@#Disala123456"
          Set-LocalUser -Name "runneradmin" -Password ($password | ConvertTo-SecureString -AsPlainText -Force)
          Write-Host "[!] Enabling RDP..."
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -value 0
          New-NetFirewallRule -DisplayName "Allow RDP" -Direction Inbound -Protocol TCP -LocalPort 3389 -Action Allow

      - name: Setup Tunnel with tmate
        shell: powershell
        run: |
          Write-Host "[!] Installing tmate..."
          # --- CORRECTED COMMAND: Using curl for a more robust download ---
          curl -L -o tmate.tar.xz "https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-windows-amd64.tar.xz"
          
          & "C:\Program Files\7-Zip\7z.exe" x tmate.tar.xz -y
          & "C:\Program Files\7-Zip\7z.exe" x tmate.tar -y
          
          Write-Host "[!] Starting tmate session..."
          $tmateDir = Resolve-Path "./tmate-*-windows-amd64" | Select-Object -First 1
          Start-Process -FilePath "$tmateDir\tmate.exe" -ArgumentList "-S tmate.sock new-session -d"
          Start-Sleep -Seconds 10
          
          Write-Host "[!] Retrieving tmate connection string..."
          $ssh_connection = & "$tmateDir\tmate.exe" -S tmate.sock display -p '#{tmate_ssh}'
          echo "TMATE_SSH=$ssh_connection" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          Write-Host "[+] tmate session is ready."

      - name: Show RDP Credentials
        shell: powershell
        run: |
          Write-Host "###################################################################" -ForegroundColor Yellow
          Write-Host "## 2-Step RDP Connection via tmate (READ INSTRUCTIONS)" -ForegroundColor Yellow
          Write-Host "###################################################################"
          Write-Host ""
          Write-Host "   STEP 1: On your PC, open CMD and run this SSH command:"
          Write-Host "   ssh -L 33890:localhost:3389 ${{ env.TMATE_SSH }}" -ForegroundColor Cyan
          Write-Host ""
          Write-Host "   STEP 2: Once connected, open Remote Desktop and connect to:"
          Write-Host "   Computer: localhost:33890" -ForegroundColor Cyan
          Write-Host ""
          Write-Host "   --- Credentials ---"
          Write-Host "   Username: runneradmin"
          Write-Host "   Password: @#Disala123456"
          Write-Host ""
          Write-Host "###################################################################"

      - name: Keep Runner Alive
        run: python time.py
