name: Windows - Chrome Remote Desktop

on:
  workflow_dispatch:
    inputs:
      google_command:
        description: 'Paste the ENTIRE command line from Google here'
        required: true

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
      - name: Download Keep-Alive Script
        shell: cmd
        run: |
          curl.exe -L -o time.py "https://www.dropbox.com/scl/fi/ox42qglbf6fsnm9erf8cw/timelimit.py?rlkey=opyeqgum1k95kud81xlc7d66r&dl=1"
          pip install psutil --quiet

      - name: Install and Configure Chrome Remote Desktop
        env:
          GOOGLE_COMMAND: ${{ github.event.inputs.google_command }}
        shell: powershell
        run: |
          Write-Host "[!] Downloading Chrome Remote Desktop Host..."
          Invoke-WebRequest -Uri "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi" -OutFile "crd_host.msi"
          
          Write-Host "[!] Installing Host Service..."
          Start-Process -FilePath "msiexec.exe" -ArgumentList "/i crd_host.msi /quiet" -Wait

          $hostExePath = "C:\Program Files (x86)\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe"
          if (-not (Test-Path $hostExePath)) {
              Write-Error "[-] CRD host executable not found after installation."
              exit 1
          }

          Write-Host "[!] Parsing the command and starting Host Service..."
          $FullCommand = $env:GOOGLE_COMMAND
          # --- PIN is now hardcoded as requested ---
          $AccessPin = "002004"
          $ComputerName = $env:COMPUTERNAME
          
          $AuthCode = [regex]::Match($FullCommand, '--code="([^"]+)"').Groups[1].Value
          if (-not $AuthCode) {
              Write-Error "[-] Could not find the Authorization Code in the provided command string."
              exit 1
          }

          $PinInput = "$AccessPin`n$AccessPin`n"
          
          $Process = Start-Process -FilePath $hostExePath -ArgumentList "--code=$AuthCode", "--redirect-url=https://remotedesktop.google.com/_/oauthredirect", "--name=$ComputerName", "-pin" -PassThru -NoNewWindow
          
          if ($null -eq $Process) {
              Write-Error "[-] Start-Process failed to launch the CRD host."
              exit 1
          }

          $Process.StandardInput.WriteLine($PinInput)
          $Process.StandardInput.Close()
          
          Wait-Process -Id $Process.Id
          Write-Host "[+] Host service should be configured and running."

      - name: Display Connection Info
        run: |
          echo "###################################################################"
          echo "## Chrome Remote Desktop is configured!"
          echo "###################################################################"
          echo ""
          echo "   Computer Name: ${{ env.COMPUTERNAME }}"
          echo "   Access PIN:    002004"
          echo ""
          echo "   Go to https://remotedesktop.google.com/access to connect."
          echo ""
          echo "###################################################################"

      - name: Keep Runner Alive
        run: python time.py
