name: Windows - RDP (All-in-One Final)

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
      - name: Install All Tools & Dependencies
        shell: cmd
        run: |
          @echo [!] Installing All Tools & Dependencies...

          rem --- Download supporting scripts ---
          curl -s -L -o time.py "https://www.dropbox.com/scl/fi/ox42qglbf6fsnm9erf8cw/timelimit.py?rlkey=opyeqgum1k95kud81xlc7d66r&dl=0"
          
          rem --- Install Python dependencies ---
          pip install psutil --quiet
          pip install pyautogui --quiet

          rem --- Download and install applications ---
          curl -s -L -o C:\Users\Public\Desktop\Telegram.exe https://telegram.org/dl/desktop/win64
          curl -s -L -o C:\Users\Public\Desktop\Winrar.exe https://www.rarlab.com/rar/winrar-x64-621.exe
          powershell -Command "Invoke-WebRequest 'https://github.com/chieunhatnang/VM-QuickConfig/releases/download/1.6.1/VMQuickConfig.exe' -OutFile 'C:\Users\Public\Desktop\VMQuickConfig.exe'"
          
          rem --- Silently install and cleanup ---
          C:\Users\Public\Desktop\Telegram.exe /VERYSILENT /NORESTART
          del C:\Users\Public\Desktop\Telegram.exe
          C:\Users\Public\Desktop\Winrar.exe /S
          del C:\Users\Public\Desktop\Winrar.exe

          rem --- Clean up desktop links ---
          del /f "C:\Users\Public\Desktop\Epic Games Launcher.lnk" > nul 2>&1
          del /f "C:\Users\Public\Desktop\Unity Hub.lnk" > nul 2>&1

          rem --- Final registry and timezone settings ---
          reg add "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\HideDesktopIcons\NewStartPanel" /v "{20D04FE0-3AEA-1069-A2D8-08002B30309D}" /t REG_DWORD /d 0 /f
          tzutil /s "Sri Lanka Standard Time"

          @echo [+] All tools installed successfully.

      - name: Configure System & Enable RDP
        shell: powershell
        run: |
          Write-Host "[!] Setting User Password..."
          $password = "@#Disala123456"
          Import-Module Microsoft.PowerShell.Security
          $securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
          Set-LocalUser -Name "runneradmin" -Password $securePassword
          Write-Host "[+] Password set successfully for 'runneradmin'."

          Write-Host "[!] Enabling RDP and Configuring Firewall..."
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -value 0
          New-NetFirewallRule -DisplayName "Allow RDP" -Direction Inbound -Protocol TCP -LocalPort 3389 -Action Allow
          Write-Host "[+] RDP Configuration Complete."

      - name: Show RDP Credentials
        shell: powershell
        run: |
          Write-Host "###############################################" -ForegroundColor Green
          Write-Host "## RDP Connection Details" -ForegroundColor Green
          Write-Host "###############################################" -ForegroundColor Green
          Write-Host ""
          $ip = (Invoke-RestMethod -Uri 'https://ifconfig.me/ip').Trim()
          Write-Host "   IP Address: $ip"
          Write-Host "   Username:   runneradmin"
          Write-Host "   Password:   @#Disala123456"
          Write-Host ""
          Write-Host "###############################################" -ForegroundColor Green

      - name: Keep Runner Alive
        run: python time.py
