name: Windows - AnyDesk Remote Access

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
      - name: Download Keep-Alive Script
        shell: cmd
        run: |
          curl.exe -L -o time.py "https://www.dropbox.com/scl/fi/ox42qglbf6fsnm9erf8cw/timelimit.py?rlkey=opyeqgum1k95kud81xlc7d66r&dl=0"
          pip install psutil --quiet

      - name: Install and Configure AnyDesk
        shell: powershell
        run: |
          $anydeskPassword = "@#Disala123456" # You can change this password
          Write-Host "[!] Downloading AnyDesk..."
          Invoke-WebRequest -Uri "https://download.anydesk.com/AnyDesk.exe" -OutFile "AnyDesk.exe"
          
          Write-Host "[!] Installing AnyDesk silently..."
          Start-Process -FilePath ".\AnyDesk.exe" -ArgumentList '--install "C:\Program Files (x86)\AnyDesk" --start-with-win --silent' -Wait
          
          Start-Sleep -Seconds 10
          
          Write-Host "[!] Setting password for Unattended Access..."
          $anydeskPassword | & "C:\Program Files (x86)\AnyDesk\AnyDesk.exe" --set-password
          
          Write-Host "[!] Retrieving AnyDesk ID..."
          $anydeskId = & "C:\Program Files (x86)\AnyDesk\AnyDesk.exe" --get-id
          
          echo "ANYDESK_ID=$anydeskId" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "ANYDESK_PASSWORD=$anydeskPassword" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          
          Write-Host "[+] AnyDesk setup complete. ID: $anydeskId"

      - name: Show AnyDesk Credentials
        run: |
          echo "###############################################"
          echo "## AnyDesk Connection Details"
          echo "###############################################"
          echo ""
          echo "   AnyDesk ID: ${{ env.ANYDESK_ID }}"
          echo "   Password:   ${{ env.ANYDESK_PASSWORD }}"
          echo ""
          echo "###############################################"

      - name: Keep Runner Alive
        run: python time.py
